### ISSUE TITLE
Channel Popouts - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by kiriiii** [Curtis-D/ChannelPopouts#16]
It doesn't seem to work with every channel for some reason
![image](https://user-images.githubusercontent.com/54556802/63723375-9b03be80-c855-11e9-98cb-059b184fdb32.png)
![image](https://user-images.githubusercontent.com/54556802/63723382-a35bf980-c855-11e9-8c33-9dfa83a9f180.png)
This is the same server

**Comment by MasicoreLord** [comment]
Pinpointed the bug to it not being able to correctly handle the unread pin icon, as your screenshot clearly shows.

**Comment by MasicoreLord** [comment]
Might fix the issue myself and send a pull request.

**Comment by MasicoreLord** [comment]
Fixed the issues and proposed the fix.
If the dev is still checking and accepts the fix, an update should come soon @kiriiii

**Comment by Curtis-D** [comment]
See https://github.com/Curtis-D/ChannelPopouts/commit/ef6daafafda18b6a4b66de11474c161c5a86a9e9
