### ISSUE TITLE
Popout does not remove server list or DM list

### ISSUE THREAD

**Issue by ZainHan33** [Curtis-D/ChannelPopouts#17]

**Comment by MasicoreLord** [comment]
Oh right that update came out, will test for that and fix that issue too along w/ the popout icon not always appearing on servers/dms/group chats.
If/when I fix it I'll PR, and the dev should likely accept it.

**Comment by MasicoreLord** [comment]
Fixed the issues and proposed the fix.
If the dev is still checking and accepts the fix, an update should come soon @ZainHan33

**Comment by ZainHan33** [comment]
Awesome thanks!

**Comment by Curtis-D** [comment]
See https://github.com/Curtis-D/ChannelPopouts/commit/ef6daafafda18b6a4b66de11474c161c5a86a9e9
