### ISSUE TITLE
Pop out not having border or title bar

### ISSUE THREAD

**Issue by Etualbadusername** [Curtis-D/ChannelPopouts#25]
![image](https://user-images.githubusercontent.com/26514609/89699935-afbb5400-d8f8-11ea-9fdf-b879dfaa27f8.png)

**Comment by iestatic** [comment]
Same, Can't figure out how to move the window after it pops out. HALP please

**Comment by AKASGaming** [comment]
I can't close it without having to fully close Discord

**Comment by YPetremann** [comment]
Same here, I'm on windows 10

**Comment by EntityReborn** [comment]
You can close it by using the window preview from the task bar. But also, bump!

**Comment by FregoRa506** [comment]
hope someone resolves this

**Comment by Pedaltothemetal** [comment]
Bump, I Tried out this plugin but the window shows no way to close the pop out
