### ISSUE TITLE
Popout window includes sidebar.

### ISSUE THREAD

**Issue by rrthrr** [Curtis-D/ChannelPopouts#8]
Popout windows now have a sidebar with server list and home button. This only started happening after a recent update to Discord.

Also as a side note, would be nice if the popout window had very limited functionality to avoid opening voice settings in a popout. 

Thanks for the plugin!

**Comment by Curtis-D** [comment]
See https://github.com/Curtis-D/ChannelPopouts/commit/ef6daafafda18b6a4b66de11474c161c5a86a9e9
